### PR TITLE
Fix guessing a timestamp format from null (Fix #25)

### LINKED ISSUE #25: NullPointerException against null for timestamp format
If the sample data includes `null` (not string-ish `"null"`) for a timestamp-like column, it threw `NullPointerException` although the exception is caught and ignored due to guess' mechanism. Fallen back to be guessed as `STRING`.

### PR DESCRIPTION
**Pull request by dmikurube**
A bug. If the sample data includes `null` (not string-ish `"null"`), it threw `NullPointerException` although the exception is caught and ignored due to guess' mechanism. Fallen back to be guessed as `STRING`.

Looking in the original Ruby CSV guess, this bug looks to have been there. But let's fix this now.

* 9f994811ded65affb73a48c4c404cc8284d34e80: reproducing the issue in a test
* 28730b73458d8033cd56f9ccf86c6ba7c6960201: fixing it

### CODE REVIEW

File: src/main/java/org/embulk/util/guess/SchemaGuess.java [hunk 1]
```diff
@@ -304,7 +304,7 @@ private GuessedType mergeTypes(final List<GuessedType> types) {
         if (t.isTimestamp()) {
             final String format = this.timeFormatGuess.guess(
                     types.stream()
-                            .map(type -> type.isTimestamp() ? type.getFormatOrTimeValue() : null)
+                            .map(type -> (type != null && type.isTimestamp()) ? type.getFormatOrTimeValue() : null)
```
Comment (vietnguyen-td) [inline src/main/java/org/embulk/util/guess/SchemaGuess.java:307]: other way, move `filter(type -> type != null)` before `map`  will avoid null check

**Review by vietnguyen-td — APPROVED** [review]
LGTM

File: src/main/java/org/embulk/util/guess/SchemaGuess.java (hunk 1 above)
Comment (dmikurube) [reply src/main/java/org/embulk/util/guess/SchemaGuess.java:307]: I thought that once, but `.map(...)` can also adds `null` again, and `.filter` is required again. So it would be more straightforward.

**Comment by dmikurube** [comment]
Thanks!
